### ISSUE TITLE
mac 报错     raise ValueError(f"Hostname {hostname} failed validation") ValueError: Hostname isv-data.oss-cn-hangzhou.aliyuncs.com failed validation

### ISSUE THREAD

**Issue by hlovingness** [modelscope/FunClip#125]

**Comment by jiayouchongmingniao** [comment]
same issue. 
ValueError: Hostname isv-data.oss-cn-hangzhou.aliyuncs.com failed validation

**Comment by jiayouchongmingniao** [comment]
ubuntu 22.04

**Comment by jiayouchongmingniao** [comment]
![1733236145902](https://github.com/user-attachments/assets/90a57d1d-6501-465d-ac7b-ee60f8917ce1)

unbeliveable, run again then successfully without any change
