### ISSUE TITLE
gradio试用问题

### ISSUE THREAD

**Issue by fallbernana123456** [modelscope/FunClip#51]
1. 使用多说话人示例视频 | Multi-speaker Demo Video 这个示例，点击识别+区分说话人，生成的结果和识别生成的一样
2. 使用文本\说话人裁剪时，待裁剪说话人 | Speaker to Clip (多个说话人使用'#'连接)这栏里该填什么内容？我除非不填，要不后台报
if str(d['spk']) == spkid and d_end-d_start>999:
KeyError: 'spk'
这个错误

**Comment by R1ckShi** [comment]
填左下角在识别说话人时出现的speaker id，例如spk1#spk3
但是确实现在不知道为什么在初次启动服务时会有speaker不生效的问题，导致不会输出speaker id
我暂时还没有定位到这个问题的原因

**Comment by ruifengma** [comment]
我也是遇到差不多的问题，多人识别跟普通识别一样，不会进行人员区分

**Comment by R1ckShi** [comment]
已经修复，重新拉取代码
