### ISSUE TITLE
目前支持的大语言模型列表

### ISSUE THREAD

**Issue by joseph16388** [modelscope/FunClip#63]
RT，谢谢！

**Comment by R1ckShi** [comment]
"qwen-plus",
"gpt-3.5-turbo", 
"gpt-3.5-turbo-0125", 
"gpt-4-turbo",
 "g4f-gpt-3.5-turbo"
也可以传入自己的模型，qwen模型会按照阿里云百炼的方式调用，gpt模型会按照openai的方式调用

**Comment by joseph16388** [comment]
> "qwen-plus", "gpt-3.5-turbo", "gpt-3.5-turbo-0125", "gpt-4-turbo", "g4f-gpt-3.5-turbo" 也可以传入自己的模型，qwen模型会按照阿里云百炼的方式调用，gpt模型会按照openai的方式调用

收到，3Q！
