### ISSUE TITLE
多人会话没有进行人员区分

### ISSUE THREAD

**Issue by ruifengma** [modelscope/FunClip#70]
用多人会话的时候，输出非多人检测的是一样，并没有进行人员区分

**Comment by R1ckShi** [comment]
一个已知的问题，并且在重新启动服务时可能解决，暂时还没有定位到

**Comment by littlerookie** [comment]
可以尝试在如下方法的参数中添加`return_spk_res=True, sentence_timestamp=False,`
![image](https://github.com/modelscope/FunClip/assets/8966194/d95e1b74-3b5b-451d-8ade-9d166f4cd30c)

**Comment by R1ckShi** [comment]
已经修复，重新拉取代码
