### ISSUE TITLE
想要打包成exe pyinstaller 打包后总是报错

### ISSUE THREAD

**Issue by allenlzg** [modelscope/FunClip#72]
想要打包exe,pyinstaller 打包后,总是找不到 gradio 的一些引用, 能换成 pywebview 写界面吗,对前端开发人员友好,可以用vue写界面,打包也方便

**Comment by R1ckShi** [comment]
短期内没有这个计划，我也尝试过pyinstaller没有成功，手动添加了gradio和funasr也不行
不过在交流群里面有人是成功了的
