### ISSUE TITLE
你好，请问funclip有没有流式接口

### ISSUE THREAD

**Issue by zzk2021** [modelscope/FunClip#73]

**Comment by R1ckShi** [comment]
funclip没有流式接口，因为即使asr过程是流式的，最终的视频裁剪也需要原始视频作为一个整体文件来裁剪
另外funasr提供开源的流式模型以及sdk服务部署方式

**Comment by zzk2021** [comment]
> funclip没有流式接口，因为即使asr过程是流式的，最终的视频裁剪也需要原始视频作为一个整体文件来裁剪 另外funasr提供开源的流式模型以及sdk服务部署方式

如果不做裁剪，只做说话人识别，funasr里有流式接口吗

**Comment by R1ckShi** [comment]
说话人识别依赖于cam++模型，根据我的了解应该没有流式模型，因为区分说话人需要长时间的音频进行说话人的聚类
具体可以移步 https://github.com/modelscope/3D-Speaker 项目
