### ISSUE TITLE
LLM根据时间戳剪辑，取值问题

### ISSUE THREAD

**Issue by littlerookie** [modelscope/FunClip#75]
<img width="584" alt="523635adab5992bb734ddafae1c2dda" src="https://github.com/modelscope/FunClip/assets/8966194/ece17bf6-f407-41ac-b13a-a41d3ed9a64c">

LLM剪辑模式下，解析时间戳，然后转成毫秒；是不是少了\*16；根据文本或者说话人切分的，都是有\*16的

<img width="429" alt="90f8fbe8f8dbb863fa774d9a82910c8" src="https://github.com/modelscope/FunClip/assets/8966194/5654558f-ee9f-4617-8690-a5344ffbab0d">

**Comment by R1ckShi** [comment]
convert_time_to_millis函数把LLM返回的"小时：分钟：秒，毫秒“格式的时间转成了毫秒

**Comment by littlerookie** [comment]
只做了毫秒转换，视频切分没有问题，音频切分的时候是有问题的；视频切分在有时间戳时，会做\*16处理，
![image](https://github.com/modelscope/FunClip/assets/8966194/344facf8-5ef2-411e-a598-8875e1f905b2)

而音频切分没有做处理

![image](https://github.com/modelscope/FunClip/assets/8966194/f5aea22f-42b2-4a8b-a397-8ce1ecd2ac5f)
