### ISSUE TITLE
处理英语视频时，裁剪出现问题

### ISSUE THREAD

**Issue by leichengjiayou** [modelscope/FunClip#78]
在命令行输入-l en启动后，识别英语视频ASR后，根据说话人进行裁剪时出现问题：
  File "/XXX/FunClip/funclip/videoclipper.py", line 221, in video_clip
    sentences = sentences.split()
AttributeError: 'list' object has no attribute 'split'

**Comment by R1ckShi** [comment]
拉取最新的代码尝试一下哈，如果还有这个问题能否上传一个能够复现错误的视频对应的音频文件
我这边运行英文时没有这个错误
<img width="1347" alt="image" src="https://github.com/modelscope/FunClip/assets/40013335/3d9733b8-4923-4b4d-b97b-dd47ed6ab2f2">

**Comment by leichengjiayou** [comment]
还是不行，我这边英语视频太大传不上去，您试试用视频而不用音频？我看代码里音频clip不会区分语言而视频vedio_clip会区分语言进行不同的处理，我猜测是不是这有bug？
