### ISSUE TITLE
请问除了千问系列和openai系列，能直接集成其他大模型吗？还是说需要重构代码？

### ISSUE THREAD

**Issue by qiuqian666** [modelscope/FunClip#92]
请问除了千问系列和openai系列，能直接集成其他大模型吗？还是说需要重构代码？

**Comment by R1ckShi** [comment]
能通过openai api调用的模型都可以，但是需要简单修改一下代码，比如在funclip/launch.py:L123这里moonshot的模型就是这样支持的
