### ISSUE TITLE
关于FunASR模型

### ISSUE THREAD

**Issue by joseph16388** [modelscope/FunClip#94]
Hello！
目前使用的punc_ct-transformer_zh-cn-common-vocab272727-pytorch，speech_campplus_sv_zh-cn_16k-common，speech_fsmn_vad_zh-cn-16k-common-pytorch这三个模型已经是FunASR系列中最准确三个模型吗？我实测了几个视频下来，生成的字幕和说话人的识别都不是太准确。是否可以通过更换模型提高识别准确度？3Q！

**Comment by R1ckShi** [comment]
punc模型可以考虑替换为词建模的https://modelscope.cn/models/iic/punc_ct-transformer_cn-en-common-vocab471067-large，可能能够解决部分由于标点模型引入的分句错误。其他的fsmn模型，asr模型和vad模型已经是最优的模型了。

**Comment by joseph16388** [comment]
> punc模型可以考虑替换为词建模的[https://modelscope.cn/models/iic/punc_ct-transformer_cn-en-common-vocab471067-large，可能能够解决部分由于标点模型引入的分句错误。其他的fsmn模型，asr模型和vad模型已经是最优的模型了。](https://modelscope.cn/models/iic/punc_ct-transformer_cn-en-common-vocab471067-large%EF%BC%8C%E5%8F%AF%E8%83%BD%E8%83%BD%E5%A4%9F%E8%A7%A3%E5%86%B3%E9%83%A8%E5%88%86%E7%94%B1%E4%BA%8E%E6%A0%87%E7%82%B9%E6%A8%A1%E5%9E%8B%E5%BC%95%E5%85%A5%E7%9A%84%E5%88%86%E5%8F%A5%E9%94%99%E8%AF%AF%E3%80%82%E5%85%B6%E4%BB%96%E7%9A%84fsmn%E6%A8%A1%E5%9E%8B%EF%BC%8Casr%E6%A8%A1%E5%9E%8B%E5%92%8Cvad%E6%A8%A1%E5%9E%8B%E5%B7%B2%E7%BB%8F%E6%98%AF%E6%9C%80%E4%BC%98%E7%9A%84%E6%A8%A1%E5%9E%8B%E4%BA%86%E3%80%82)

好的，感谢！
