### ISSUE TITLE
识别 |ASR慢死了，三分钟的视频，识别，一个多小时还在队列中

### ISSUE THREAD

**Issue by tianqing8011** [modelscope/FunClip#97]
如标题：识别 |ASR慢死了，三分钟的视频，识别，一个多小时还在队列中

**Comment by R1ckShi** [comment]
如果是创空间体验，使用人多了慢是正常的。如果是本机部署，要看你自己的设备性能。一般3分钟的视频几十秒就会识别完毕。

**Comment by tianqing8011** [comment]
这是我的本机设备：设备名称
USER-20230824PD
处理器
11th Gen Intel(R)Core(TM) ***@***.*** 2.59GHz
机带 RAM
16.0 GB (15.9 GB 可用)
设备 ID
D55C637E-486C-43FE-BBB0-51BC05FDB971
产品 ID
00330-80000-00000-AA247系统类型
64 位操作系统, 基于 x64 的处理器
笔和触控
没有可用于此显示器的笔或触控输入。我是本地部署的，视频识别了两个小时还没是没反应，在哪可以看到处理日志，是不是哪里出问题了

**Comment by R1ckShi** [comment]
在你执行python脚本的那个终端里面能看到程序输出的log

**Comment by Chi8wah** [comment]
> 同问，我用 A100 跑4分钟的 ASR+SD 跑了40多分钟还在跑，控制台也没 log，我甚至怀疑是不是断连或者卡死了。之前在魔塔别人的空间上体验的时候虽然也超级慢，但好歹也能跑完，本地部署反而跑不完是有点搞不明白。 

破案了，是因为本地部署的时候，一直在尝试加载那几个示例，把网络进程卡住了，没法处理其他请求，导致按什么按钮都是假的。把示例删掉之后再部署就好了。 anyway，说话人识别还是达不到预期 T T

**Comment by kof8855** [comment]
还有别的AI剪辑类可以推荐吗
